<?php

//use Zend\Version;
use Zend\Version\Version;

function debug_to_console($data) {

    if (is_array($data))
        $output = "<script>console.log( 'Debug Objects: " . implode(',', $data) . "' );</script>";
    else
        $output = "<script>console.log( 'Debug Objects: " . $data . "' );</script>";

    echo $output;
}

function getLocale($data) {
    //\Locale::acceptFromHttp($this->request->getHeader()); 
    //\Locale::acceptFromHttp(getHeader()); 
    $lang = \Locale::acceptFromHttp($_SERVER['HTTP_ACCEPT_LANGUAGE']);
    debug_to_console("Language as reported by PHP: " . $lang . " in File" . $data);
}
?>

<?php getLocale("Layout.phtml"); ?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                //->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/theme.css')
        //->prependStylesheet($this->basePath() . '/css/justified-nav.css')
//                        ->prependStylesheet($this->basePath() . '/css/app.min.css') 
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container nav-contain">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
<!--                    <a class="navbar-brand" href="< ?php echo $this->url('home') ?>"><img src="< ?php echo $this->basePath('img/logo.png') ?>" alt="Badenfahrt"/>&nbsp;< ?php echo $this->translate('Skeleton Application') ?></a>-->
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Badenfahrt"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="">
                            <a id="scroll-to-about" href="/#about">About</a>
                        </li>
                        <li>
                            <a href="/#info">Info</a>
                        </li>
                        <li>

                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-close-others="false" data-delay="1000" data-hover="dropdown" data-toggle="dropdown" href="#">
                                Applications
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="active">
                                    <a id="scroll-to-home" href="/album">Album</a>
                                </li>
                                <li>
                                    <a href="/blog">Blog</a>
                                </li>
                                </ul>
                        </li>
                        <!--li class="dropdown active"-->
                            <li class="dropdown">
                            <a class="dropdown-toggle" data-close-others="false" data-delay="1000" data-hover="dropdown" data-toggle="dropdown" href="#">
                                UserManagement
                                <b class="caret"></b>
                                <!--b class="glyphicon glyphicon-align-justify"></b-->
                            </a>
                            <ul class="dropdown-menu">

                                <li role="presentation" class="dropdown-header">Eigener Test <b class="caret"></b></li>
                                <li>
                                    <a href="/users"><b class="glyphicon glyphicon-user"></b>&nbsp;&nbsp;&nbsp;MyUser</a>
                                </li>
                                <li role="presentation" class="dropdown-header">Fremdmodule <b class="caret"></b></li>
                                
                            </ul>
                        </li>


                    </ul>
                    <!--                        <form class="navbar-form navbar-right">
                                                  <input type="text" class="form-control" placeholder="Search...">
                                            </form> -->

                    <!--                            <div class="input-group">
                                                    <input id="glyph-search" class="form-control" type="text" placeholder="Search">
                                                    <span class="input-group-btn">
                                                        <button id="filter-clear" class="btn btn-default" type="button">X</button>
                                                    </span>
                                                </div>-->

                    <form class="navbar-form navbar-right">
                        <div class="form-group">
                            <input type="text" placeholder="Email" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="password" placeholder="Password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                    </form> 

<!--                    <div class="navbar-form navbar-right">
                        <div class="form-group"> 
                            <input id="glyph-search" class="form-control" type="text" placeholder="Search">

                            <button id="filter-clear" class="btn btn-info" type="button">X</button>

                        </div>
                    </div>-->


                </div>
            </div>
        </nav>



        <div class="container">


            <?php echo $this->content; ?>



            <hr>
        </div> <!-- /container -->
        <footer class="footer affix affix-bottom">
            <div class="container"> 
                <p>&copy; 2013 - <?php echo date('Y') ?> by A. Vogelbacher. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>

        <?php echo $this->inlineScript() ?>

    </body>
</html>
